//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: pecan.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// ==========================================
/// UI -> Server Communication
/// ==========================================
///
/// Usage: instantiate `Pecan_ClientServiceClient`, then call methods of this protocol to make API calls.
public protocol Pecan_ClientServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Pecan_ClientServiceClientInterceptorFactoryProtocol? { get }

  func streamEvents(
    callOptions: CallOptions?,
    handler: @escaping (Pecan_ServerMessage) -> Void
  ) -> BidirectionalStreamingCall<Pecan_ClientMessage, Pecan_ServerMessage>
}

extension Pecan_ClientServiceClientProtocol {
  public var serviceName: String {
    return "pecan.ClientService"
  }

  /// Bidirectional stream for the UI client to talk to the Server
  ///
  /// Callers should use the `send` method on the returned object to send messages
  /// to the server. The caller should send an `.end` after the final message has been sent.
  ///
  /// - Parameters:
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ClientStreamingCall` with futures for the metadata and status.
  public func streamEvents(
    callOptions: CallOptions? = nil,
    handler: @escaping (Pecan_ServerMessage) -> Void
  ) -> BidirectionalStreamingCall<Pecan_ClientMessage, Pecan_ServerMessage> {
    return self.makeBidirectionalStreamingCall(
      path: Pecan_ClientServiceClientMetadata.Methods.streamEvents.path,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeStreamEventsInterceptors() ?? [],
      handler: handler
    )
  }
}

@available(*, deprecated)
extension Pecan_ClientServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Pecan_ClientServiceNIOClient")
public final class Pecan_ClientServiceClient: Pecan_ClientServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Pecan_ClientServiceClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Pecan_ClientServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the pecan.ClientService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Pecan_ClientServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Pecan_ClientServiceNIOClient: Pecan_ClientServiceClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Pecan_ClientServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the pecan.ClientService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Pecan_ClientServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// ==========================================
/// UI -> Server Communication
/// ==========================================
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Pecan_ClientServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Pecan_ClientServiceClientInterceptorFactoryProtocol? { get }

  func makeStreamEventsCall(
    callOptions: CallOptions?
  ) -> GRPCAsyncBidirectionalStreamingCall<Pecan_ClientMessage, Pecan_ServerMessage>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Pecan_ClientServiceAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Pecan_ClientServiceClientMetadata.serviceDescriptor
  }

  public var interceptors: Pecan_ClientServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeStreamEventsCall(
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncBidirectionalStreamingCall<Pecan_ClientMessage, Pecan_ServerMessage> {
    return self.makeAsyncBidirectionalStreamingCall(
      path: Pecan_ClientServiceClientMetadata.Methods.streamEvents.path,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeStreamEventsInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Pecan_ClientServiceAsyncClientProtocol {
  public func streamEvents<RequestStream>(
    _ requests: RequestStream,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Pecan_ServerMessage> where RequestStream: Sequence, RequestStream.Element == Pecan_ClientMessage {
    return self.performAsyncBidirectionalStreamingCall(
      path: Pecan_ClientServiceClientMetadata.Methods.streamEvents.path,
      requests: requests,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeStreamEventsInterceptors() ?? []
    )
  }

  public func streamEvents<RequestStream>(
    _ requests: RequestStream,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Pecan_ServerMessage> where RequestStream: AsyncSequence & Sendable, RequestStream.Element == Pecan_ClientMessage {
    return self.performAsyncBidirectionalStreamingCall(
      path: Pecan_ClientServiceClientMetadata.Methods.streamEvents.path,
      requests: requests,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeStreamEventsInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Pecan_ClientServiceAsyncClient: Pecan_ClientServiceAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Pecan_ClientServiceClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Pecan_ClientServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public protocol Pecan_ClientServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'streamEvents'.
  func makeStreamEventsInterceptors() -> [ClientInterceptor<Pecan_ClientMessage, Pecan_ServerMessage>]
}

public enum Pecan_ClientServiceClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "ClientService",
    fullName: "pecan.ClientService",
    methods: [
      Pecan_ClientServiceClientMetadata.Methods.streamEvents,
    ]
  )

  public enum Methods {
    public static let streamEvents = GRPCMethodDescriptor(
      name: "StreamEvents",
      path: "/pecan.ClientService/StreamEvents",
      type: GRPCCallType.bidirectionalStreaming
    )
  }
}

/// ==========================================
/// Agent -> Server Communication
/// ==========================================
///
/// Usage: instantiate `Pecan_AgentServiceClient`, then call methods of this protocol to make API calls.
public protocol Pecan_AgentServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Pecan_AgentServiceClientInterceptorFactoryProtocol? { get }

  func connect(
    callOptions: CallOptions?,
    handler: @escaping (Pecan_HostCommand) -> Void
  ) -> BidirectionalStreamingCall<Pecan_AgentEvent, Pecan_HostCommand>
}

extension Pecan_AgentServiceClientProtocol {
  public var serviceName: String {
    return "pecan.AgentService"
  }

  /// Bidirectional stream for the isolated Agent to talk to the Server
  ///
  /// Callers should use the `send` method on the returned object to send messages
  /// to the server. The caller should send an `.end` after the final message has been sent.
  ///
  /// - Parameters:
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ClientStreamingCall` with futures for the metadata and status.
  public func connect(
    callOptions: CallOptions? = nil,
    handler: @escaping (Pecan_HostCommand) -> Void
  ) -> BidirectionalStreamingCall<Pecan_AgentEvent, Pecan_HostCommand> {
    return self.makeBidirectionalStreamingCall(
      path: Pecan_AgentServiceClientMetadata.Methods.connect.path,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeConnectInterceptors() ?? [],
      handler: handler
    )
  }
}

@available(*, deprecated)
extension Pecan_AgentServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Pecan_AgentServiceNIOClient")
public final class Pecan_AgentServiceClient: Pecan_AgentServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Pecan_AgentServiceClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Pecan_AgentServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the pecan.AgentService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Pecan_AgentServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Pecan_AgentServiceNIOClient: Pecan_AgentServiceClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Pecan_AgentServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the pecan.AgentService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Pecan_AgentServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// ==========================================
/// Agent -> Server Communication
/// ==========================================
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Pecan_AgentServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Pecan_AgentServiceClientInterceptorFactoryProtocol? { get }

  func makeConnectCall(
    callOptions: CallOptions?
  ) -> GRPCAsyncBidirectionalStreamingCall<Pecan_AgentEvent, Pecan_HostCommand>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Pecan_AgentServiceAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Pecan_AgentServiceClientMetadata.serviceDescriptor
  }

  public var interceptors: Pecan_AgentServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeConnectCall(
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncBidirectionalStreamingCall<Pecan_AgentEvent, Pecan_HostCommand> {
    return self.makeAsyncBidirectionalStreamingCall(
      path: Pecan_AgentServiceClientMetadata.Methods.connect.path,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeConnectInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Pecan_AgentServiceAsyncClientProtocol {
  public func connect<RequestStream>(
    _ requests: RequestStream,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Pecan_HostCommand> where RequestStream: Sequence, RequestStream.Element == Pecan_AgentEvent {
    return self.performAsyncBidirectionalStreamingCall(
      path: Pecan_AgentServiceClientMetadata.Methods.connect.path,
      requests: requests,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeConnectInterceptors() ?? []
    )
  }

  public func connect<RequestStream>(
    _ requests: RequestStream,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Pecan_HostCommand> where RequestStream: AsyncSequence & Sendable, RequestStream.Element == Pecan_AgentEvent {
    return self.performAsyncBidirectionalStreamingCall(
      path: Pecan_AgentServiceClientMetadata.Methods.connect.path,
      requests: requests,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeConnectInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Pecan_AgentServiceAsyncClient: Pecan_AgentServiceAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Pecan_AgentServiceClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Pecan_AgentServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public protocol Pecan_AgentServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'connect'.
  func makeConnectInterceptors() -> [ClientInterceptor<Pecan_AgentEvent, Pecan_HostCommand>]
}

public enum Pecan_AgentServiceClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "AgentService",
    fullName: "pecan.AgentService",
    methods: [
      Pecan_AgentServiceClientMetadata.Methods.connect,
    ]
  )

  public enum Methods {
    public static let connect = GRPCMethodDescriptor(
      name: "Connect",
      path: "/pecan.AgentService/Connect",
      type: GRPCCallType.bidirectionalStreaming
    )
  }
}

/// ==========================================
/// UI -> Server Communication
/// ==========================================
///
/// To build a server, implement a class that conforms to this protocol.
public protocol Pecan_ClientServiceProvider: CallHandlerProvider {
  var interceptors: Pecan_ClientServiceServerInterceptorFactoryProtocol? { get }

  /// Bidirectional stream for the UI client to talk to the Server
  func streamEvents(context: StreamingResponseCallContext<Pecan_ServerMessage>) -> EventLoopFuture<(StreamEvent<Pecan_ClientMessage>) -> Void>
}

extension Pecan_ClientServiceProvider {
  public var serviceName: Substring {
    return Pecan_ClientServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "StreamEvents":
      return BidirectionalStreamingServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Pecan_ClientMessage>(),
        responseSerializer: ProtobufSerializer<Pecan_ServerMessage>(),
        interceptors: self.interceptors?.makeStreamEventsInterceptors() ?? [],
        observerFactory: self.streamEvents(context:)
      )

    default:
      return nil
    }
  }
}

/// ==========================================
/// UI -> Server Communication
/// ==========================================
///
/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Pecan_ClientServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Pecan_ClientServiceServerInterceptorFactoryProtocol? { get }

  /// Bidirectional stream for the UI client to talk to the Server
  func streamEvents(
    requestStream: GRPCAsyncRequestStream<Pecan_ClientMessage>,
    responseStream: GRPCAsyncResponseStreamWriter<Pecan_ServerMessage>,
    context: GRPCAsyncServerCallContext
  ) async throws
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Pecan_ClientServiceAsyncProvider {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Pecan_ClientServiceServerMetadata.serviceDescriptor
  }

  public var serviceName: Substring {
    return Pecan_ClientServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  public var interceptors: Pecan_ClientServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "StreamEvents":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Pecan_ClientMessage>(),
        responseSerializer: ProtobufSerializer<Pecan_ServerMessage>(),
        interceptors: self.interceptors?.makeStreamEventsInterceptors() ?? [],
        wrapping: { try await self.streamEvents(requestStream: $0, responseStream: $1, context: $2) }
      )

    default:
      return nil
    }
  }
}

public protocol Pecan_ClientServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'streamEvents'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeStreamEventsInterceptors() -> [ServerInterceptor<Pecan_ClientMessage, Pecan_ServerMessage>]
}

public enum Pecan_ClientServiceServerMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "ClientService",
    fullName: "pecan.ClientService",
    methods: [
      Pecan_ClientServiceServerMetadata.Methods.streamEvents,
    ]
  )

  public enum Methods {
    public static let streamEvents = GRPCMethodDescriptor(
      name: "StreamEvents",
      path: "/pecan.ClientService/StreamEvents",
      type: GRPCCallType.bidirectionalStreaming
    )
  }
}
/// ==========================================
/// Agent -> Server Communication
/// ==========================================
///
/// To build a server, implement a class that conforms to this protocol.
public protocol Pecan_AgentServiceProvider: CallHandlerProvider {
  var interceptors: Pecan_AgentServiceServerInterceptorFactoryProtocol? { get }

  /// Bidirectional stream for the isolated Agent to talk to the Server
  func connect(context: StreamingResponseCallContext<Pecan_HostCommand>) -> EventLoopFuture<(StreamEvent<Pecan_AgentEvent>) -> Void>
}

extension Pecan_AgentServiceProvider {
  public var serviceName: Substring {
    return Pecan_AgentServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Connect":
      return BidirectionalStreamingServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Pecan_AgentEvent>(),
        responseSerializer: ProtobufSerializer<Pecan_HostCommand>(),
        interceptors: self.interceptors?.makeConnectInterceptors() ?? [],
        observerFactory: self.connect(context:)
      )

    default:
      return nil
    }
  }
}

/// ==========================================
/// Agent -> Server Communication
/// ==========================================
///
/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Pecan_AgentServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Pecan_AgentServiceServerInterceptorFactoryProtocol? { get }

  /// Bidirectional stream for the isolated Agent to talk to the Server
  func connect(
    requestStream: GRPCAsyncRequestStream<Pecan_AgentEvent>,
    responseStream: GRPCAsyncResponseStreamWriter<Pecan_HostCommand>,
    context: GRPCAsyncServerCallContext
  ) async throws
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Pecan_AgentServiceAsyncProvider {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Pecan_AgentServiceServerMetadata.serviceDescriptor
  }

  public var serviceName: Substring {
    return Pecan_AgentServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  public var interceptors: Pecan_AgentServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Connect":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Pecan_AgentEvent>(),
        responseSerializer: ProtobufSerializer<Pecan_HostCommand>(),
        interceptors: self.interceptors?.makeConnectInterceptors() ?? [],
        wrapping: { try await self.connect(requestStream: $0, responseStream: $1, context: $2) }
      )

    default:
      return nil
    }
  }
}

public protocol Pecan_AgentServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'connect'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeConnectInterceptors() -> [ServerInterceptor<Pecan_AgentEvent, Pecan_HostCommand>]
}

public enum Pecan_AgentServiceServerMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "AgentService",
    fullName: "pecan.AgentService",
    methods: [
      Pecan_AgentServiceServerMetadata.Methods.connect,
    ]
  )

  public enum Methods {
    public static let connect = GRPCMethodDescriptor(
      name: "Connect",
      path: "/pecan.AgentService/Connect",
      type: GRPCCallType.bidirectionalStreaming
    )
  }
}
